<dynamic-fields :fields="[{
	name: 'length',
	label: '@lang('kitchen/dimensions.length')',
	value: '{{ old('length', $application->length != 0 ? $application->length  : '') }}',
	readonly: {{ !$application->isOpen() ? 'true' : 'false'}},
	type: 'text',
	subType: 'number',
	placeholder: '@lang('kitchen/dimensions.inMeters')',
	error: {{ $errors->has('length') ? collect($errors->get('length')) : 'null'}},
},{
	name : 'width',
	label : '@lang('kitchen/dimensions.width')',
	value: '{{ old('width', $application->length != 0 ? $application->length  : '') }}',
	readonly: {{ ! $application->isOpen() ? 'true' : 'false'}},
	type: 'text',
	subType: 'number',
	placeholder: '@lang('kitchen/dimensions.inMeters')',
	error: {{ $errors->has('width') ? collect($errors->get('width')) : 'null'}},
},{
	name : 'terrace_length',
	label : '@lang('kitchen/dimensions.terraceLength')',
	value: '{{ old('terrace_length', $application->terrace_length) }}',
	readonly: {{ ! $application->isOpen() ? 'true' : 'false'}},
	type: 'text',
	subType: 'number',
	placeholder: '@lang('kitchen/dimensions.inMeters')',
    error: {{ $errors->has('terrace_length') ? collect($errors->get('terrace_length')) :  'null'}},
},{
	name : 'terrace_width',
	label : '@lang('kitchen/dimensions.terraceWidth')',
	value: '{{ old('terrace_width', $application->terrace_width) }}',
	readonly: {{ ! $application->isOpen() ? 'true' : 'false'}},
	type: 'text',
	subType: 'number',
	placeholder: '@lang('kitchen/dimensions.inMeters')',
    error: {{ $errors->has('terrace_width') ? collect($errors->get('terrace_width')) : 'null'}},
}D]">
</dynamic-fields>