<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BandMember extends Model {

	protected static function boot() {
		parent::boot(); // TODO: Change the autogenerated stub
		static::deleted(function ($bandMember)  {
			$bandMember->user->delete();
		});
	}
	public function user(){
		return $this->morphOne(User::class, 'user');
	}

	public function band(){
		return $this->belongsTo(Band::class);
	}
}
