<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model {
    protected $fillable = ['name', 'value'];

    public static function all($columns = ['*']) {
        $settings = parent::all($columns);
        $settings->push(Setting::registrationYear());
        return $settings; // TODO: Change the autogenerated stub
    }

    public static function registrationYear(){
        return  new Setting(['name' => 'registration_year', 'value' => date('Y' ) + 1]);
    }
}
